name: Publish Github Pages

on:
  push:
    branches:
      # Put these back to enable publishing to github pages
      # - main
      # - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install --frozen-lockfile -s --ignore-scripts
      - name: Build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
